### ISSUE TITLE
Can't compile in xcode7 with iOS 9 SDK

### ISSUE THREAD

**Issue by BrainFeverMedia** [kstenerud/ObjectAL-for-iPhone#85]
Trying to build latest version in Xcode 7.0 beta with iOS 9.0 sdk. Getting a bunch of link errors in ALWrapper.o.

```
Undefined symbols for architecture arm64:
  "_alGetBufferfv", referenced from:
      +[ALWrapper getBufferfv:parameter:values:] in ALWrapper.o
  "_alBuffer3f", referenced from:
      +[ALWrapper buffer3f:parameter:v1:v2:v3:] in ALWrapper.o
  "_alBufferf", referenced from:
      +[ALWrapper bufferf:parameter:value:] in ALWrapper.o
  "_alBufferData", referenced from:
      +[ALWrapper bufferData:format:data:size:frequency:] in ALWrapper.o
  "_alIsBuffer", referenced from:
      +[ALWrapper isBuffer:] in ALWrapper.o
  "_alDeleteBuffers", referenced from:
      +[ALWrapper deleteBuffers:numBuffers:] in ALWrapper.o
```  

Compile and link fails both for devices and simulator. I'll report back if I can discover anything.

**Comment by kstenerud** [comment]
That's bizarre... Those are API calls to OpenAL. Is the OpenAL library linked in?

**Comment by BrainFeverMedia** [comment]
I'm using the latest version of ObjectAL which includes the OpenAL source. I'm not linking any OpenAL libs.

**Comment by kstenerud** [comment]
The `OpenAL` library is provided by Apple, and needs to be linked in. ObjectAL sits on top of OpenAL.

**Comment by BrainFeverMedia** [comment]
Adding OpenAL.framework fixed it. Strange because ObjectAL compiles/links with the iOS8 sdk without the OpenAL.framework. Thanks for your help!

**Comment by pasta12** [comment]
The [iOS 9 API diffs](https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/index.html#//apple_ref/doc/uid/TP40016222) show OpenAL as being removed. Is that going to be a problem? Sounds like @BrainFeverMedia was still able to link against it?
