### ISSUE TITLE
How do I save applied filter audio file ?

### ISSUE THREAD

**Issue by K-IOS** [kstenerud/ObjectAL-for-iPhone#90]
I have used few filter and trying to save that audio file in document directory but still can not find any way to do that task.
waiting for your kind reply.
Thanks in advance !

**Comment by kstenerud** [comment]
I'm not sure what it is you are trying to do. Can you elaborate?

**Comment by K-IOS** [comment]
I have used following code to applied pitch,gain and pan effect In audio and Its working fine :+1 
 
[OALSimpleAudio sharedInstance].reservedSources = 0;
 source = [ALSource source];
 buffer = [[OALSimpleAudio sharedInstance] preloadEffect:self.strAudioUrl reduceToMono:YES];
 [source play:buffer gain:0.5 pitch:1.0 pan:0.5 loop:YES];

But Now I want to save that audio in device with effect.

**Comment by K-IOS** [comment]
Have you understand my question ? 
I just want to saved Audio file with Applied effect . Currently In your project we can only apply effect and Play that audio. There is no method to save that audio file.

**Comment by kstenerud** [comment]
Ah ok, unfortunately, the `OpenAL` system that ObjectAL uses doesn't save processed audio to disk (only raw audio, recorded directly from the microphone). For that, you need to use `Audio Units`.
