### ISSUE TITLE
CocoaPods issue

### ISSUE THREAD

**Issue by mikemonaco** [kstenerud/ObjectAL-for-iPhone#91]
pod 'ObjectAL-for-iPhone', '~> 2.5'

When trying to #import <ObjectAL/ObjectAL.h>, I am getting the following error:

Pods/Headers/Public/ObjectAL-for-iPhone/ObjectAL/ObjectAL.h:31:9: 'OALAction.h' file not found

Using Xcode 6.4. Assuming something is up with the header mapping in the podspec?

**Comment by vovkasm** [comment]
Can you test, this pull request #88 (Fix pod spec for cocoapods 0.39.0)?

**Comment by mikemonaco** [comment]
yup, this works!

On Thu, Nov 19, 2015 at 2:27 AM, Vladimir Timofeev <notifications@github.com
